"""baseline

Revision ID: 1f5ed9eb034a
Revises:
Create Date: 2026-06-12 01:42:35.056274

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1f5ed9eb034a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
