"""baseline

Revision ID: 1f5ed9eb034a
Revises:
Create Date: 2026-06-12 01:42:35.056274

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1f5ed9eb034a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
