"""Canonical Jinja template paths used by route handlers."""


class TemplateNames:
    ACCOUNT = "pages/account.html"
    ADMIN = "pages/admin.html"
    AUTHOR_DETAIL = "pages/author_detail.html"
    AUTHORS = "pages/authors.html"
    CHANGE_PASSWORD = "pages/change_password.html"
    CHAPTER = "pages/chapter.html"
    CHAPTER_PATTERNS = "pages/chapter_patterns.html"
    ERROR = "pages/error.html"
    FORGOT_PASSWORD = "pages/forgot_password.html"
    INDEX = "pages/index.html"
    LOGIN = "pages/login.html"
    LOGS = "pages/logs.html"
    OFFLINE_DATA = "pages/offline_data.html"
    RESET_PASSWORD = "pages/reset_password.html"
    SEARCH = "pages/search.html"
    SEARCH_RESULTS = "partials/search_results.html"
    SETTINGS = "pages/settings.html"
    STATS = "pages/stats.html"
    STORY = "pages/story.html"
    STORY_FILES = "partials/story_files.html"
    USER_FORM = "pages/user_form.html"
    USERS = "pages/users.html"
